trigger:
  batch: true
  branches:
    include:
      - main

# ==========================================
# VARIABLES
# ==========================================
variables:
  imageRepository: node-aks-app
  dockerfilePath: app/Dockerfile
  buildContext: app
  tag: $(Build.BuildId)

stages:

# ==========================================
# STAGE 1 - TERRAFORM (CREATE ACR + VM)
# Runs on Microsoft Hosted Agent
# ==========================================
- stage: TerraformInfra
  displayName: Create ACR + VM

  jobs:
    - job: Terraform
      pool:
        vmImage: ubuntu-latest

      steps:
        - checkout: self

        - task: TerraformInstaller@1
          inputs:
            terraformVersion: latest

        - task: TerraformTaskV4@4
          displayName: Terraform Init
          inputs:
            provider: azurerm
            command: init
            workingDirectory: infra
            backendServiceArm: 'azure-rm-service-connection'
            backendAzureRmResourceGroupName: 'tf-backend-rg'
            backendAzureRmStorageAccountName: 'tfstatestorage292929'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'acr-terraform.tfstate'

        - task: TerraformTaskV4@4
          displayName: Terraform Plan
          inputs:
            provider: azurerm
            command: plan
            workingDirectory: infra
            environmentServiceNameAzureRM: 'azure-rm-service-connection'

        - task: TerraformTaskV4@4
          displayName: Terraform Apply
          inputs:
            provider: azurerm
            command: apply
            workingDirectory: infra
            environmentServiceNameAzureRM: 'azure-rm-service-connection'
            args: '-auto-approve -lock-timeout=10m'


# ==========================================
# STAGE 2 - DOCKER DEPLOY (SELF-HOSTED VM)
# Runs on YOUR VM agent
# ==========================================
- stage: DeployOnVM
  displayName: Deploy on Self-Hosted VM
  dependsOn: TerraformInfra

  jobs:
    - job: Deploy
      pool:
        name: Default   # 👈 YOUR SELF-HOSTED AGENT POOL NAME

      steps:
        - checkout: self

        # Login to Azure Container Registry
        - task: AzureCLI@2
          displayName: Login to ACR
          inputs:
            azureSubscription: 'azure-rm-service-connection'
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az acr login --name noderegistrydemo12345

        # Build Docker image on VM
        - script: |
            docker build -t noderegistrydemo12345.azurecr.io/node-aks-app:$(tag) -f app/Dockerfile app
          displayName: Build Docker Image

        # Push Docker image to ACR
        - script: |
            docker push noderegistrydemo12345.azurecr.io/node-aks-app:$(tag)
          displayName: Push Docker Image

        # Run container on SAME VM
        - script: |
            docker stop nodeapp || true
            docker rm nodeapp || true
            docker run -d -p 80:3000 --name nodeapp noderegistrydemo12345.azurecr.io/node-aks-app:$(tag)
          displayName: Run Container