trigger:
  batch: true
  branches:
    include:
      - main

variables:
  imageRepository: node-aks-app
  dockerfilePath: app/Dockerfile
  buildContext: app
  tag: $(Build.BuildId)

  # Terraform variables
  TF_VAR_resource_group_name: "tfstate-rg"
  TF_VAR_location: "East US"
  TF_VAR_acr_name: "noderegistrydemo12345"
  TF_VAR_vm_name: "node-vm"
  TF_VAR_vm_size: "Standard_B1s"
  TF_VAR_vm_admin_username: "azureuser"
  TF_VAR_vm_admin_password: "StrongPass@123!"
  TF_VAR_dns_label: "nodevm12345"

stages:

# ==========================================
# STAGE 1 - TERRAFORM (USE MICROSOFT AGENT)
# ==========================================
- stage: TerraformInfra
  displayName: Terraform Infrastructure

  jobs:
    - job: Terraform
      pool:
        vmImage: ubuntu-latest   # ✅ IMPORTANT FIX

      steps:
        - checkout: self

        - task: TerraformInstaller@1
          inputs:
            terraformVersion: latest

        - task: TerraformTaskV4@4
          displayName: Terraform Init
          inputs:
            provider: azurerm
            command: init
            backendServiceArm: 'azure-rm-service-connection'
            backendAzureRmResourceGroupName: 'tf-backend-rg'
            backendAzureRmStorageAccountName: 'tfstatestorage292929'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'acr-terraform.tfstate'
            workingDirectory: infra

        - task: TerraformTaskV4@4
          displayName: Terraform Apply
          inputs:
            provider: azurerm
            command: apply
            workingDirectory: infra
            environmentServiceNameAzureRM: 'azure-rm-service-connection'
            args: '-auto-approve -lock-timeout=10m'