trigger:
  - main

pool:
  name: node-docker-aks

variables:
  ACR_NAME: nodeacr98y0j
  IMAGE_NAME: node-docker-aks
  IMAGE_TAG: $(Build.BuildId)

stages:

- stage: DeployToAKS
  displayName: Deploy to AKS

  jobs:
  - job: AKSDeploy
    displayName: AKS Deployment Job

    steps:

    # ==========================================
    # CHECKOUT
    # ==========================================
    - checkout: self

    # ==========================================
    # LOGIN TO AKS
    # ==========================================
    - task: AzureCLI@2
      displayName: AKS Login
      inputs:
        azureSubscription: 'aks-service-connection'
        scriptType: bash
        scriptLocation: inlineScript
        inlineScript: |
          az aks get-credentials \
            --resource-group tfstate-milan-rg \
            --name node-aks-demo-milan \
            --overwrite-existing

    # ==========================================
    # UPDATE IMAGE
    # ==========================================
    - script: |
        kubectl set image deployment/node-docker-aks \
        node-docker-aks=$(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(IMAGE_TAG)
      displayName: Update AKS Image

    # ==========================================
    # VERIFY ROLLOUT
    # ==========================================
   
    # ==========================================
    # VERIFY DEPLOYMENT
    # ==========================================
    - script: |
        kubectl get pods
        kubectl get svc
        kubectl get ingress
      displayName: Verify Deployment