trigger:
  - main

pool:
  name: node-docker-aks

stages:

# ==========================================
# DEPLOY TO AKS
# ==========================================
- stage: DeployToAKS

  displayName: Deploy Application to AKS

  jobs:

    - job: AKSDeployment

      displayName: AKS Deployment Job

      steps:

        # ==========================================
        # CHECKOUT CODE
        # ==========================================
        - checkout: self

        # ==========================================
        # LOGIN TO AKS
        # ==========================================
        - task: AzureCLI@2

          displayName: AKS Login

          inputs:
            azureSubscription: 'aks-service-connection'

            scriptType: bash
            scriptLocation: inlineScript

            inlineScript: |
              az aks get-credentials \
                --resource-group tfstate-milan-rg \
                --name node-aks-demo-milan \
                --overwrite-existing

        # ==========================================
        # DEPLOY TO AKS
        # ==========================================
        - script: |
            kubectl apply -f k8s/deployment.yaml
            kubectl apply -f k8s/service.yaml
            kubectl apply -f k8s/ingress.yaml

          displayName: Deploy Kubernetes Resources

        # ==========================================
        # VERIFY
        # ==========================================
        - script: |
            kubectl get pods
            kubectl get svc
            kubectl get ingress

          displayName: Verify Deployment