trigger:
  batch: true
  branches:
    include:
      - main

  paths:
    include:
      - app/*
      - Dockerfile
      - pipelines/docker-deploy.yml

variables:
  tag: $(Build.BuildId)

  ACR_NAME: nodeacr98y0j 
  IMAGE_NAME: node-docker-aks
  CONTAINER_NAME: nodeapp

stages:

- stage: DockerDeploy
  displayName: Docker Build and Deploy

  jobs:
    - job: DeployContainer

      pool:
        name: node-docker-aks

      steps:

        # ==========================================
        # CHECKOUT REPO
        # ==========================================
        - checkout: self

        # ==========================================
        # DEBUG STRUCTURE
        # ==========================================
        - script: |
            pwd
            ls -R
          displayName: Debug Repo Structure

        # ==========================================
        # LOGIN TO ACR
        # ==========================================
        - task: AzureCLI@2
          displayName: Azure Login + ACR Login
          inputs:
            azureSubscription: 'azure-rm-service-connection'
            scriptType: bash
            scriptLocation: inlineScript
            inlineScript: |
              az acr login --name $(ACR_NAME)

        # ==========================================
        # BUILD IMAGE
        # ==========================================
        - script: |
            docker build \
              -t $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(tag) \
              -f Dockerfile .
          displayName: Build Docker Image

        # ==========================================
        # PUSH IMAGE
        # ==========================================
        - script: |
            docker push $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(tag)
          displayName: Push Docker Image

        # ==========================================
        # REMOVE OLD CONTAINER
        # ==========================================
        - script: |
            docker stop $(CONTAINER_NAME) || true
            docker rm $(CONTAINER_NAME) || true
          displayName: Remove Old Container

        # ==========================================
        # RUN NEW CONTAINER
        # ==========================================
        - script: |
            docker run -d \
              --name $(CONTAINER_NAME) \
              -p 3000:3000 \
              --restart unless-stopped \
              $(ACR_NAME).azurecr.io/$(IMAGE_NAME):$(tag)
          displayName: Run New Container

        # ==========================================
        # VERIFY
        # ==========================================
        - script: |
            docker ps
          displayName: Verify Running Container