trigger:
  batch: true
  branches:
    include:
      - main

variables:
  imageRepository: node-aks-app
  dockerfilePath: app/Dockerfile
  buildContext: app
  tag: $(Build.BuildId)

stages:

# ==========================================
# STAGE 1 - TERRAFORM
# ==========================================
- stage: TerraformInfra
  displayName: "Terraform Infra"

  jobs:
    - job: Terraform
      pool:
        vmImage: ubuntu-latest

      steps:
        - checkout: self

        - task: TerraformInstaller@1
          inputs:
            terraformVersion: latest

        - task: TerraformTaskV4@4
          displayName: Terraform Init
          inputs:
            provider: azurerm
            command: init
            workingDirectory: infra
            backendServiceArm: 'azure-rm-service-connection'
            backendAzureRmResourceGroupName: 'tf-backend-rg'
            backendAzureRmStorageAccountName: 'tfstatestorage292929'
            backendAzureRmContainerName: 'tfstate'
            backendAzureRmKey: 'acr-terraform.tfstate'

        - task: TerraformTaskV4@4
          displayName: Terraform Validate
          inputs:
            provider: azurerm
            command: validate
            workingDirectory: infra

        - task: TerraformTaskV4@4
          displayName: Terraform Plan
          inputs:
            provider: azurerm
            command: plan
            workingDirectory: infra
            environmentServiceNameAzureRM: 'azure-rm-service-connection'

        - task: TerraformTaskV4@4
          displayName: Terraform Apply
          inputs:
            provider: azurerm
            command: apply
            workingDirectory: infra
            commandOptions: '-auto-approve -lock-timeout=10m'
            environmentServiceNameAzureRM: 'azure-rm-service-connection'
